### ISSUE TITLE
ID field not working

### ISSUE THREAD

**Issue by RufinoHonorato** [spandl/DS-strava-connector#7]
Hi

While using Strava explorer connector (nice job ny the way!) ID field is not working.
Every time I add ID to a table or try to see values from the Data Studio explorer I get this error:

Data Studio cannot connect to your dataset.
Could not get the data from the underlying dataset
Error ID: e11f8e51

I'm using this connector:
Connector ID PROD
https://datastudio.google.com/datasources/create?connectorId=AKfycbyWOEf16aZ8F3rephvvxkO1p0-U5yz-Dqt3Y44fE429t0v76Nu_djgAZJmkyt8piSWs4w

Many thanks
Regards

**Comment by spandl** [comment]
Hi,

I can confirm this behaviour. I will need to see why this happens.

Out of curiosity: What are you using the ID field for?

**Comment by RufinoHonorato** [comment]
Hi,

I'm using the connector to summarise activities in data studio reports.

The use case is simple, when planning a ride I need to search for specific past rides, by distance, elapsed time, name of the activity, etc. i.e. tomorrow I have just 2 hours and I would like to repeat an specific previous ride that took me 2 hours...

Once you search thru the activities and identify the right one I would like to include two links (URLs) one to the activity in strava:

https://www.strava.com/activities/ID

And one to the export_gpx feature to get the GPX file for that route and load into my Garmin GPS device for navigation, so I can repeat the same route.

https://www.strava.com/activities/ID/export_gpx

 I need the ID to create two new fields with the URLs.

Thanks
Regards

**Comment by spandl** [comment]
Smart. No promis on timeline, but I have added this onto my to-do list. If it is nothing major it will go faster.

**Comment by RufinoHonorato** [comment]
Many thanks for your answer, of course It's not urgent just a nice to have, so don't worry for the timeline.

Great piece of work this connector!

Regards

**Comment by spandl** [comment]
The connector has just been updated. 

* The ID field is now working properly.
* Added also Gear ID (which returns only ID - but from there it is easy to identify gear and create a Data Blend with a Google Sheet)

![image](https://user-images.githubusercontent.com/5740594/103181732-571e3080-4872-11eb-8ef3-4d85e691ce9f.png)

Enjoy!

**Comment by RufinoHonorato** [comment]
Many thanks!! I'll try it.

Just a question, what is the "Gear ID"? For what could It be used?

Best Regards

**Comment by spandl** [comment]
The gear ID corresponds to the bikes/shoes that you can specify in your settings

![image](https://user-images.githubusercontent.com/5740594/103223414-30084300-48f4-11eb-87fa-9d7bc1dfcbde.png)

**Comment by RufinoHonorato** [comment]
Got It!!

Everything working right now!

URL to the activity and also link to the GPX file download.

![Screenshot 2020-12-28 at 17 03 45](https://user-images.githubusercontent.com/73540915/103227524-d1ac8600-492e-11eb-8fda-0acd6298216c.png)

Many thanks and happy new year!
